---
kind: pipeline
name: default
type: kubernetes
platform:
  os: linux
  arch: amd64

steps:
# - name: build
#   pull: always
#   image: golang:1.12
#   commands:
#     - make dep
#     - make build

- name: docker build and push to quay
  image: plugins/docker
  settings:
    registry: quay.io
    dockerfile: Dockerfile
    repo: quay.io/ukhomeofficedigital/drone-rocketchat
    tags:
    - latest
    - ${DRONE_COMMIT_SHA}
    - build-${DRONE_BUILD_NUMBER}
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
      event:
      - push
      #branch:
      #- master

trigger:
  event:
  - push
  # branch:
  # - master
  
services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

---
kind: pipeline
name: after
type: kubernetes

steps:
- name: notify
  image: quay.io/ukhomeofficedigital/drone-rocketchat
  settings:
    url:
      from_secret: rocket_url
    user_id:
      from_secret: rocket_id
    token:
      from_secret: rocket_token
    channel:
      from_secret: rocket_channel
    message: "test"

depends_on:
- default

trigger:
  status:
  - success
  - failure
