---
kind: pipeline
name: default
type: kubernetes
platform:
  os: linux
  arch: amd64

steps:
# - name: Sonar Security Scan
#   pull: if-not-exists
#   image: quay.io/ukhomeofficedigital/sonar-scanner:latest
#   when:
#     event:
#     - push

- name: docker build and push to quay
  image: plugins/docker
  settings:
    registry: quay.io
    dockerfile: Dockerfile
    repo: quay.io/ukhomeofficedigital/drone-rockdghfetchat
    tags:
    - latest
    - ${DRONE_COMMIT_SHA}
    - build-${DRONE_BUILD_NUMBER}
    command:
    - env
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
      event:
      - push
     # branch:
     # - master
  


# - name: notification2
#   image: quay.io/ukhomeofficedigital/drone-rocketchat:latest
#   pull: if-not-exists
#   when:
#     status: [ success, failure ]
#   settings:
#     username: "Test"
#     icon: 
#      - value: ":sos:"
#        when:
#           DRONE_BUILD_STATUS: failure
#      - value: ":white_check_mark:"
#        when:
#           DRONE_BUILD_STATUS: success
#     title:
#       - value: "Build Number ${DRONE_BUILD_NUMBER} Successful"
#         when:
#           DRONE_BUILD_STATUS: success
#       - value: "Build Number ${DRONE_BUILD_NUMBER} Failed"
#         when:
#           DRONE_BUILD_STATUS: failure
#     text:
#       - value: "Commit by ${DRONE_COMMIT_AUTHOR} : ${DRONE_COMMIT_MESSAGE}"
#         when:
#           DRONE_BUILD_STATUS: success
#       - value: "Commit by ${DRONE_COMMIT_AUTHOR} : ${DRONE_COMMIT_MESSAGE}"
#         when:
#           DRONE_BUILD_STATUS: failure
#     color:
#       - value: "#2DE0A5"
#         when:
#           DRONE_BUILD_STATUS: success
#       - value: "#e30d0d"
#         when:
#           DRONE_BUILD_STATUS: failure
#     webhook: 
#       from_secret: dev_webhook
#     command:
#     - sh scripts/run.sh

- name: notification
  image: quay.io/ukhomeofficedigital/drone-rocketchat:buil-4
  when:
      status: [ success, failure ]
  settings:
    webhook:
      from_secret: dev_webhook
    username: DroneCI
    color: 
      - value: green
        when:
          DRONE_BUILD_STATUS: success
      - value: red
        when:
          DRONE_BUILD_STATUS: failure          
    message:
      - value: "Build: ${DRONE_BUILD_NUMBER} succeeded. Good job."
        when:
          DRONE_BUILD_STATUS: success
      - value: "Build: ${DRONE_BUILD_NUMBER} failed. Fix me please."      
    text: ${DRONE_COMMIT_MESSAGE}
    fields:
      - title: Author
        value: ${DRONE_COMMIT_AUTHOR}
      - title: Demo
        value:
        when:
          DRONE_COMMIT_BRANCH:
            - master
            - production
    
services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
