---
kind: pipeline
name: default
type: kubernetes
platform:
  os: linux
  arch: amd64

steps:
- name: docker build and push to quay
  image: plugins/docker
  settings:
    registry: quay.io
    dockerfile: Dockerfile
    repo: quay.io/ukhomeofficedigital/drone-rocketchat
    tags:
    - latest
    - ${DRONE_COMMIT_SHA}
    - build-${DRONE_BUILD_NUMBER}
    command:
    - env
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_passwordd
  when:
      event:
      - push
---
kind: pipeline
name: after
type: kubernetes

steps:
- name: notification
  image: quay.io/ukhomeofficedigital/drone-rocketchat:latest
  pull: if-not-exists
  settings:
    username: "Test"
    icon:
      - value: ":sos:"
    title:
      - value: "Build Number #${DRONE_BUILD_NUMBER} : ${DRONE_BUILD_STATUS}"
    text:
      - value: "Commit by ${DRONE_COMMIT_AUTHOR} : ${DRONE_COMMIT_MESSAGE} "
    color:
      - value: "#E02D2D"
    webhook:
      from_secret: dev_webhook
  command:
    - printenv
    - echo "DRONE_BUILD_STATUS:$DRONE_BUILD_STATUS"
    - echo "DRONE_STAGE_STATUS:$DRONE_STAGE_STATUS"
    - echo "DRONE_JOB_STATUS:$DRONE_JOB_STATUS"
    - echo "CI_BUILD_STATUS:$CI_BUILD_STATUS"
    - echo "CI_JOB_STATUS:$CI_JOB_STATUS"
    - echo "BUILD_STATUS:$BUILD_STATUS"
    - sh scripts/run.sh
  when:
    event:
    - push
    - tag
    status:
    - success
    - failure

depends_on:
- default

trigger:
  status:
  - success
  - failure


services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
